# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8065/api/v4/offices
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-CSRF-Token: p5xniqn15jbt7j1mh4up9wr37o
X-Requested-With: XMLHttpRequest

{
  "app_id": "app_id",
  "name": "office2",
  "preview": "preview",
  "description": "description",
  "active": true,

  "lat": "1",
  "long": "2"
}

###
GET http://localhost:8065/api/v4/offices
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-CSRF-Token: p5xniqn15jbt7j1mh4up9wr37o
X-Requested-With: XMLHttpRequest


###
DELETE http://localhost:8065/api/v4/offices/iskwjjg1dbfkmb8o3f8wk839rw
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-CSRF-Token: p5xniqn15jbt7j1mh4up9wr37o
X-Requested-With: XMLHttpRequest


###
