# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8065/api/v4/posts/search
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-CSRF-Token: p5xniqn15jbt7j1mh4up9wr37o
X-Requested-With: XMLHttpRequest

{"terms":"2","include_deleted_channels":false,"time_zone_offset":14400,"page":0,"per_page":20}

###
